In [1]:
import pandas as pd

In [2]:
data = pd.read_excel('online_retail_II.xlsx')
data

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom

In [3]:
data.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID           float64
Country                object
dtype: object

In [4]:
data.isnull().sum() / len(data) * 100

Invoice         0.000000
StockCode       0.000000
Description     0.557225
Quantity        0.000000
InvoiceDate     0.000000
Price           0.000000
Customer ID    20.539488
Country         0.000000
dtype: float64

In [5]:
data['Description'] = data['Description'].fillna(data['Description'].mode())

In [6]:
data['Description'] = data['Description'].fillna(data['Description'].ffill())

In [7]:
data['Customer ID'].max()

18287.0

In [8]:
data['Customer ID'].min()

12346.0

In [9]:
data['Customer ID'] = data['Customer ID'].fillna(data['Customer ID'].median())

In [10]:
data.duplicated().sum()

6865

In [11]:
data.drop_duplicates(inplace=True)

In [12]:
data['Country'].value_counts()

Country
United Kingdom          479047
EIRE                      9660
Germany                   8120
France                    5754
Netherlands               2768
Spain                     1271
Switzerland               1187
Portugal                  1098
Belgium                   1053
Channel Islands            906
Sweden                     901
Italy                      729
Australia                  654
Cyprus                     546
Austria                    537
Greece                     517
United Arab Emirates       432
Denmark                    428
Norway                     369
Finland                    354
Unspecified                310
USA                        244
Japan                      224
Poland                     194
Malta                      172
Lithuania                  154
Singapore                  117
RSA                        111
Bahrain                    107
Canada                      77
Hong Kong                   76
Thailand                    76
Israel                      74
Iceland                     71
Korea                       63
Brazil                      62
West Indies                 54
Bermuda                     34
Nigeria                     32
Lebanon                     13
Name: count, dtype: int64

In [13]:
data['Revenue'] = data['Quantity'] * data['Price']

In [14]:
data['Country'].value_counts()

Country
United Kingdom          479047
EIRE                      9660
Germany                   8120
France                    5754
Netherlands               2768
Spain                     1271
Switzerland               1187
Portugal                  1098
Belgium                   1053
Channel Islands            906
Sweden                     901
Italy                      729
Australia                  654
Cyprus                     546
Austria                    537
Greece                     517
United Arab Emirates       432
Denmark                    428
Norway                     369
Finland                    354
Unspecified                310
USA                        244
Japan                      224
Poland                     194
Malta                      172
Lithuania                  154
Singapore                  117
RSA                        111
Bahrain                    107
Canada                      77
Hong Kong                   76
Thailand                    76
Israel                      74
Iceland                     71
Korea                       63
Brazil                      62
West Indies                 54
Bermuda                     34
Nigeria                     32
Lebanon                     13
Name: count, dtype: int64

In [15]:
data.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [17]:
uk = data[data['Country']=='United Kingdom']

In [19]:
uk['Price'].sum()

2189586.5730000003

In [42]:
uk['Quantity'].sum()

4410572

In [ ]:
data['Revenue'] = data['Quantity'] * data['Price']

In [34]:
data.groupby('Country')[['Revenue','Quantity']].sum().sort_values(by='Quantity',ascending=False)

                          Revenue  Quantity
Country
United Kingdom        8161692.763   4410572
Denmark                 46972.950    227030
EIRE                   352235.680    188659
Netherlands            263861.760    181822
Germany                195920.421    107026
France                 130661.550     74317
Sweden                  51190.110     52226
Switzerland             43343.410     22053
Australia               30051.800     20053
Spain                   37052.130     18317
Belgium                 22644.030     11974
Portugal                23765.230     11875
Channel Islands         21367.320     10994
Norway                   4079.570      7863
Italy                   13774.390      7285
Japan                    8435.960      6604
Austria                 13023.280      6479
Greece                  14284.970      6151
United Arab Emirates     8046.370      5746
Cyprus                  11173.800      4356
Finland                  7187.710      3651
Unspecified              4937.530      3416
Bermuda                  1253.140      2798
USA                      4555.620      2666
Thailand                 3070.540      2552
Lithuania                4892.680      2306
Hong Kong                3922.260      2306
Poland                   3314.950      1991
Singapore                4037.770      1753
RSA                      2366.720      1618
Malta                    2686.750      1547
Israel                   3199.400      1132
Bahrain                  2313.150      1015
Canada                   1216.660       894
Iceland                  1323.320       828
Korea                     949.820       598
West Indies               536.410       395
Brazil                    268.270       189
Lebanon                   172.030        71
Nigeria                    -6.660        56

In [28]:
data.groupby('Country')['Revenue'].sum().sort_values(ascending=False)

Country
United Kingdom          8161692.763
EIRE                     352235.680
Netherlands              263861.760
Germany                  195920.421
France                   130661.550
Sweden                    51190.110
Denmark                   46972.950
Switzerland               43343.410
Spain                     37052.130
Australia                 30051.800
Portugal                  23765.230
Belgium                   22644.030
Channel Islands           21367.320
Greece                    14284.970
Italy                     13774.390
Austria                   13023.280
Cyprus                    11173.800
Japan                      8435.960
United Arab Emirates       8046.370
Finland                    7187.710
Unspecified                4937.530
Lithuania                  4892.680
USA                        4555.620
Norway                     4079.570
Singapore                  4037.770
Hong Kong                  3922.260
Poland                     3314.950
Israel                     3199.400
Thailand                   3070.540
Malta                      2686.750
RSA                        2366.720
Bahrain                    2313.150
Iceland                    1323.320
Bermuda                    1253.140
Canada                     1216.660
Korea                       949.820
West Indies                 536.410
Brazil                      268.270
Lebanon                     172.030
Nigeria                      -6.660
Name: Revenue, dtype: float64

In [26]:
data['Revenue'] = data['Quantity'] * data['Price']

In [27]:
data.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [30]:
uk_revenue = 2189586.573
uk_revenue / data['Revenue'].sum() * 100

23.034275933174143

In [33]:
data['Description'].value_counts().to_dict()

{'WHITE HANGING HEART T-LIGHT HOLDER': 3530,
 'REGENCY CAKESTAND 3 TIER': 2220,
 'STRAWBERRY CERAMIC TRINKET BOX': 1814,
 'ASSORTED COLOUR BIRD ORNAMENT': 1463,
 'PACK OF 72 RETRO SPOT CAKE CASES': 1449,
 '60 TEATIME FAIRY CAKE CASES': 1402,
 'HOME BUILDING BLOCK WORD': 1361,
 'JUMBO BAG RED RETROSPOT': 1305,
 'LUNCH BAG RED SPOTTY': 1279,
 'JUMBO STORAGE BAG SUKI': 1222,
 'BAKING SET 9 PIECE RETROSPOT ': 1212,
 'REX CASH+CARRY JUMBO SHOPPER': 1184,
 'PACK OF 60 PINK PAISLEY CAKE CASES': 1183,
 'WOODEN FRAME ANTIQUE WHITE ': 1182,
 'LUNCH BAG  BLACK SKULL.': 1166,
 'LUNCH BAG SUKI  DESIGN ': 1142,
 'HEART OF WICKER LARGE': 1134,
 'LOVE BUILDING BLOCK WORD': 1121,
 'RED HANGING HEART T-LIGHT HOLDER': 1112,
 'JUMBO BAG STRAWBERRY': 1095,
 'JUMBO SHOPPER VINTAGE RED PAISLEY': 1082,
 'SWEETHEART CERAMIC TRINKET BOX': 1078,
 'HEART OF WICKER SMALL': 1067,
 'HOT WATER BOTTLE TEA AND SYMPATHY': 1041,
 'PARTY BUNTING': 1039,
 'SCOTTIE DOG HOT WATER BOTTLE': 1030,
 'VINTAGE SNAP CARDS': 1028,
 'JUMBO  BAG BAROQUE BLACK WHITE': 1003,
 'LUNCH BAG SPACEBOY DESIGN ': 1001,
 "PAPER CHAIN KIT 50'S CHRISTMAS ": 992,
 'LUNCH BAG CARS BLUE': 985,
 'HANGING HEART ZINC T-LIGHT HOLDER': 979,
 'WOODEN PICTURE FRAME WHITE FINISH': 976,
 'LUNCH BAG WOODLAND': 976,
 'SET/20 RED SPOTTY PAPER NAPKINS ': 963,
 'SMALL POPCORN HOLDER': 963,
 'CHOCOLATE HOT WATER BOTTLE': 958,
 'ANTIQUE SILVER TEA GLASS ETCHED': 945,
 'SET/5 RED SPOTTY LID GLASS BOWLS': 942,
 'ZINC METAL HEART DECORATION': 929,
 'POSTAGE': 906,
 'FELTCRAFT 6 FLOWER FRIENDS': 903,
 '72 SWEETHEART FAIRY CAKE CASES': 902,
 'GIN + TONIC DIET METAL SIGN': 894,
 'Manual': 894,
 'NATURAL SLATE HEART CHALKBOARD ': 874,
 '6 RIBBONS RUSTIC CHARM': 873,
 'RECYCLING BAG RETROSPOT ': 863,
 'PACK OF 72 SKULL CAKE CASES': 857,
 'PLEASE ONE PERSON METAL SIGN': 849,
 'VINTAGE UNION JACK BUNTING': 848,
 'VICTORIAN GLASS HANGING T-LIGHT': 843,
 'LUNCH BAG PINK RETROSPOT': 842,
 'PINK CREAM FELT CRAFT TRINKET BOX ': 833,
 'HAND OVER THE CHOCOLATE   SIGN ': 829,
 'RED WOOLLY HOTTIE WHITE HEART.': 823,
 'JUMBO BAG PINK WITH WHITE SPOTS': 821,
 'RETRO SPOT TEA SET CERAMIC 11 PC ': 818,
 'CREAM HEART CARD HOLDER': 814,
 'RED SPOTTY CHARLOTTE BAG': 803,
 'PAPER BUNTING RETRO SPOTS': 799,
 'JUMBO BAG PINK VINTAGE PAISLEY': 788,
 'WOODLAND CHARLOTTE BAG': 781,
 'JUMBO BAG SCANDINAVIAN PAISLEY': 778,
 'RED GINGHAM ROSE JEWELLERY BOX': 776,
 'PACK OF 6 BIRDY GIFT TAGS': 772,
 'DOTCOM POSTAGE': 771,
 'VINTAGE HEADS AND TAILS CARD GAME ': 767,
 'RED RETROSPOT CAKE STAND': 760,
 'BATHROOM METAL SIGN': 746,
 'COOK WITH WINE METAL SIGN ': 745,
 'RED TOADSTOOL LED NIGHT LIGHT': 744,
 'WOOD S/3 CABINET ANT WHITE FINISH': 741,
 'HANGING HEART JAR T-LIGHT HOLDER': 740,
 'PACK OF 60 DINOSAUR CAKE CASES': 729,
 'FELTCRAFT BUTTERFLY HEARTS': 723,
 'PAPER CHAIN KIT VINTAGE CHRISTMAS': 705,
 'ROUND SNACK BOXES SET OF4 WOODLAND ': 704,
 'STRAWBERRY CHARLOTTE BAG': 697,
 'JUMBO BAG OWLS': 695,
 'DOOR MAT UNION FLAG': 690,
 'NO SINGING METAL SIGN': 687,
 'PLASTERS IN TIN SPACEBOY': 684,
 'COLOUR GLASS T-LIGHT HOLDER HANGING': 682,
 'SINGLE HEART ZINC T-LIGHT HOLDER': 679,
 'PLASTERS IN TIN CIRCUS PARADE ': 678,
 'PINK BLUE FELT CRAFT TRINKET BOX': 677,
 'HAND WARMER OWL DESIGN': 676,
 'PACK 20 ENGLISH ROSE PAPER NAPKINS': 675,
 'LADIES & GENTLEMEN METAL SIGN': 673,
 'WOOD 2 DRAWER CABINET WHITE FINISH': 671,
 'GRAND CHOCOLATECANDLE': 669,
 'JUMBO STORAGE BAG SKULLS': 653,
 'HAND WARMER SCOTTY DOG DESIGN': 652,
 'EDWARDIAN PARASOL NATURAL': 649,
 'KNITTED UNION FLAG HOT WATER BOTTLE': 642,
 'LOVEBIRD HANGING DECORATION WHITE ': 640,
 'HEART IVORY TRELLIS SMALL': 640,
 'HANGING JAM JAR T-LIGHT HOLDER': 631,
 'HAND WARMER BIRD DESIGN': 631,
 'FAWN BLUE HOT WATER BOTTLE': 629,
 'POTTERING IN THE SHED METAL SIGN': 629,
 'POTTING SHED TEA MUG': 624,
 'PLASTERS IN TIN VINTAGE PAISLEY ': 621,
 'RECIPE BOX PANTRY YELLOW DESIGN': 621,
 'PACK OF 60 SPACEBOY CAKE CASES': 617,
 'PLASTERS IN TIN WOODLAND ANIMALS': 617,
 'HEART FILIGREE DOVE  SMALL': 615,
 'SET OF 3 HEART COOKIE CUTTERS': 615,
 'HOT BATHS METAL SIGN': 613,
 'ROUND SNACK BOXES SET OF 4 FRUITS ': 611,
 'CREAM CUPID HEARTS COAT HANGER': 610,
 'EDWARDIAN PARASOL BLACK': 604,
 'PAPER CHAIN KIT RETRO SPOT': 601,
 'JUMBO BAG WOODLAND ANIMALS': 595,
 'JUMBO BAG SPACEBOY DESIGN': 594,
 'RIBBON REEL STRIPES DESIGN ': 593,
 'WOODEN BOX OF DOMINOES': 592,
 'BOX OF 24 COCKTAIL PARASOLS': 588,
 'PACK OF 60 MUSHROOM CAKE CASES': 583,
 'PLASTERS IN TIN SKULLS': 582,
 'SMALL GLASS HEART TRINKET POT': 582,
 'COLOUR GLASS. STAR T-LIGHT HOLDER': 579,
 'CHARLOTTE BAG SUKI DESIGN': 569,
 'SMALL HEART MEASURING SPOONS': 568,
 'JUMBO BAG RED WHITE SPOTTY ': 565,
 'GARDENERS KNEELING PAD': 564,
 'SET OF 72 RETRO SPOT PAPER  DOILIES': 560,
 'BEWARE OF THE CAT METAL SIGN ': 556,
 'SET OF 20 VINTAGE CHRISTMAS NAPKINS': 555,
 'IVORY KITCHEN SCALES': 555,
 'BAKING SET SPACEBOY DESIGN': 553,
 'CERAMIC STRAWBERRY CAKE MONEY BANK': 552,
 'LARGE POPCORN HOLDER ': 552,
 'PAPER BUNTING WHITE LACE': 551,
 'JUMBO BAG TOYS ': 549,
 'WOOD BLACK BOARD ANT WHITE FINISH': 548,
 'VINTAGE UNION JACK CUSHION COVER': 548,
 'HEART IVORY TRELLIS LARGE': 547,
 'RETRO SPOT LARGE MILK JUG': 543,
 'SPACEBOY LUNCH BOX ': 543,
 'RED SPOTTY BISCUIT TIN': 542,
 'METAL 4 HOOK HANGER FRENCH CHATEAU': 538,
 'DOLLY GIRL LUNCH BOX': 536,
 'MINI CAKE STAND  HANGING STRAWBERY': 535,
 'TEA TIME CAKE STAND IN GIFT BOX': 533,
 'CHOCOLATE THIS WAY METAL SIGN': 532,
 'TOILET METAL SIGN': 532,
 'CHILLI LIGHTS': 531,
 'PINK HEART SHAPE EGG FRYING PAN': 528,
 'SPACEBOY BIRTHDAY CARD': 526,
 'SET OF 72 PINK HEART PAPER DOILIES': 526,
 'PARTY METAL SIGN ': 525,
 'PACK OF 12 HEARTS DESIGN TISSUES ': 525,
 'WHITE SKULL HOT WATER BOTTLE ': 522,
 'RED SPOTTY SHOPPER BAG': 522,
 '12 PENCILS SMALL TUBE SKULL': 520,
 'TOY TIDY PINK RETROSPOT  ': 518,
 'RED RETROSPOT TRADITIONAL TEAPOT ': 516,
 'WORLD WAR 2 GLIDERS ASSTD DESIGNS': 515,
 'HAND WARMER UNION JACK': 513,
 'CHICK GREY HOT WATER BOTTLE': 512,
 'I CAN ONLY PLEASE ONE PERSON MUG': 512,
 'FELTCRAFT DOLL ROSIE': 511,
 'RED 3 PIECE MINI DOTS CUTLERY SET': 509,
 'WICKER STAR ': 509,
 'WHITE WOOD GARDEN PLANT LADDER': 509,
 'FELTCRAFT DOLL MOLLY': 507,
 'WOODEN SCHOOL COLOURING SET': 505,
 'STRAWBERRY LUNCH BOX WITH CUTLERY': 504,
 'PICNIC BASKET WICKER SMALL': 501,
 'PINK DOUGHNUT TRINKET POT ': 500,
 'ASSORTED COLOURS SILK FAN': 500,
 'RED RETROSPOT SMALL MILK JUG': 499,
 'PINK HAPPY BIRTHDAY BUNTING': 498,
 'TEA PARTY BIRTHDAY CARD': 498,
 'GREY HEART HOT WATER BOTTLE': 495,
 'SET OF 36 TEATIME PAPER DOILIES': 494,
 'KEY FOB , SHED': 492,
 'SCANDINAVIAN REDS RIBBONS': 491,
 'HEART FILIGREE DOVE LARGE': 491,
 'METAL SIGN TAKE IT OR LEAVE IT ': 491,
 'BLUE 3 PIECE MINI DOTS CUTLERY SET': 490,
 'FELTCRAFT CUSHION BUTTERFLY': 489,
 '60 CAKE CASES VINTAGE CHRISTMAS': 488,
 'GUMBALL COAT RACK': 488,
 'ASSTD DESIGN BUBBLE GUM RING': 484,
 'BINGO SET': 483,
 'SET/6 RED SPOTTY PAPER PLATES': 482,
 'RED SPOTTY ROUND CAKE TINS': 479,
 'TEA BAG PLATE RED SPOTTY ': 476,
 'PLASTERS IN TIN STRONGMAN': 475,
 'CLOTHES PEGS RETROSPOT PACK 24 ': 475,
 'HANGING METAL HEART LANTERN': 474,
 'MEMO BOARD COTTAGE DESIGN': 470,
 'DOOR MAT NEW ENGLAND': 470,
 'LARGE HEART MEASURING SPOONS': 469,
 'SAVE THE PLANET MUG': 469,
 '3 HEARTS HANGING DECORATION RUSTIC': 469,
 'CREAM SWEETHEART MINI CHEST': 468,
 'PINK 3 PIECE MINI DOTS CUTLERY SET': 468,
 'RED SPOT HEART HOT WATER BOTTLE': 467,
 'DOORMAT HEARTS': 466,
 'MEMO BOARD RETROSPOT  DESIGN': 466,
 'SILVER HANGING T-LIGHT HOLDER': 466,
 'FELTCRAFT CUSHION RABBIT': 465,
 'SET OF 3 BUTTERFLY COOKIE CUTTERS': 464,
 'TEA TIME OVEN GLOVE': 463,
 'TRADITIONAL WOODEN SKIPPING ROPE': 463,
 'SET OF 36 PAISLEY FLOWER DOILIES': 461,
 'FOUR HOOK  WHITE LOVEBIRDS': 461,
 'VINTAGE SNAKES & LADDERS': 458,
 'TEA TIME TEA TOWELS ': 458,
 'WOODEN BOX ADVENT CALENDAR ': 457,
 'TRADITIONAL WOODEN CATCH CUP GAME ': 456,
 'HOME SWEET HOME METAL SIGN ': 456,
 'PACK OF 72 RETROSPOT CAKE CASES': 455,
 'HAND WARMER RED RETROSPOT': 451,
 'FELTCRAFT CUSHION OWL': 450,
 'SET 12 KIDS COLOUR  CHALK STICKS': 450,
 'WHITE METAL LANTERN': 449,
 'RED SPOTTY CUP': 449,
 'SET/20 STRAWBERRY PAPER NAPKINS ': 448,
 'WASHROOM METAL SIGN': 448,
 'RED KITCHEN SCALES': 445,
 'SET/6 RED SPOTTY PAPER CUPS': 438,
 'COFFEE MUG CAT + BIRD DESIGN': 434,
 'FOOD CONTAINER SET 3 LOVE HEART ': 433,
 'TEA TIME PARTY BUNTING': 432,
 'LUNCH BOX WITH CUTLERY RETROSPOT ': 432,
 'LARGE CAKE STAND  HANGING STRAWBERY': 432,
 'RED SPOTTY BOWL': 431,
 'SET/2 RED SPOTTY TEA TOWELS ': 431,
 'HOME SWEET HOME MUG': 430,
 'RED/WHITE DOTS RUFFLED UMBRELLA': 430,
 'RED RETROSPOT PICNIC BAG': 429,
 'GROW YOUR OWN PLANT IN A CAN ': 428,
 'DOORSTOP RETROSPOT HEART': 428,
 'SWALLOWS GREETING CARD': 428,
 'STRAWBERRY   PICNIC BAG': 427,
 'LUNCH BOX I LOVE LONDON': 427,
 'RETRO RED SPOTTY WASHING UP GLOVES': 426,
 'VICTORIAN SEWING BOX LARGE': 426,
 'CERAMIC HEART FAIRY CAKE MONEY BANK': 425,
 "I'M ON HOLIDAY METAL SIGN": 424,
 'EDWARDIAN PARASOL RED': 422,
 'SUKI  SHOULDER BAG': 422,
 'FELTCRAFT DOLL EMILY': 421,
 'WHITE SPOT RED CERAMIC DRAWER KNOB': 420,
 'BLACK HEART CARD HOLDER': 419,
 'ENGLISH ROSE DESIGN PEG BAG': 418,
 'TOY TIDY SPACEBOY  ': 418,
 'LAUNDRY 15C METAL SIGN': 418,
 'PACK OF 6 PANNETONE GIFT BOXES': 417,
 'KITCHEN METAL SIGN': 417,
 'DOOR MAT RED SPOT': 416,
 'ASSORTED COLOUR MINI CASES': 414,
 'PLACE SETTING WHITE HEART': 414,
 'FOLKART ZINC HEART CHRISTMAS DEC': 414,
 'NATURAL SLATE RECTANGLE CHALKBOARD': 413,
 'BLUE SPOT CERAMIC DRAWER KNOB': 412,
 'WHITE SPOT BLUE CERAMIC DRAWER KNOB': 412,
 'KEY FOB , BACK DOOR ': 410,
 'SET OF 3 NOTEBOOKS IN PARCEL': 410,
 'TRAVEL SEWING KIT': 409,
 'TRADITIONAL CHRISTMAS RIBBONS': 409,
 'SET/3 RUSSIAN DOLL STACKING TINS': 408,
 'HOT WATER BOTTLE I AM SO POORLY': 408,
 'RED  HARMONICA IN BOX ': 406,
 'SWEETHEART KEY CABINET': 405,
 'VICTORIAN SEWING BOX SMALL ': 405,
 'DOORMAT UNION FLAG': 404,
 'WOODEN ROUNDERS GARDEN SET ': 400,
 'GREEN REGENCY TEACUP AND SAUCER': 400,
 'BLUE HARMONICA IN BOX ': 400,
 'RED STRIPE CERAMIC DRAWER KNOB': 400,
 'BLUE STRIPE CERAMIC DRAWER KNOB': 400,
 'GINGHAM HEART  DOORSTOP RED': 400,
 'RETRO COFFEE MUGS ASSORTED': 399,
 'CHRISTMAS TOILET ROLL': 398,
 'WHITE DOVE HONEYCOMB PAPER GARLAND': 397,
 'SET/10 RED SPOTTY PARTY CANDLES': 397,
 '4 TRADITIONAL SPINNING TOPS': 396,
 'IVORY HANGING DECORATION  HEART': 396,
 'ROSES REGENCY TEACUP AND SAUCER ': 396,
 'GLITTER BUTTERFLY CLIPS': 395,
 'ROUND SNACK BOXES SET OF 4 SKULLS': 395,
 'NATURAL SLATE CHALKBOARD LARGE ': 395,
 "FANNY'S REST STOPMETAL SIGN": 395,
 'DOOR MAT FAIRY CAKE': 394,
 'PAPER CHAIN KIT EMPIRE': 394,
 'PAPER BUNTING COLOURED LACE': 394,
 "PINK FAIRY CAKE CHILD'S APRON": 393,
 'FILIGRIS HEART WITH BUTTERFLY': 393,
 'PACK OF 12 SUKI TISSUES ': 393,
 'SET/10 PINK SPOTTY PARTY CANDLES': 392,
 '12 PENCILS SMALL TUBE RED SPOTTY': 391,
 'FIRST AID TIN': 390,
 'TRADITIONAL MODELLING CLAY': 390,
 'SET 7 BABUSHKA NESTING BOXES': 389,
 'AREA PATROLLED METAL SIGN': 389,
 'RETRO SPOT CAKE STAND': 389,
 'ZINC WILLIE WINKIE  CANDLE STICK': 389,
 'PAINTED METAL PEARS ASSORTED': 388,
 '3 STRIPEY MICE FELTCRAFT': 387,
 'PICTURE DOMINOES': 386,
 'CORONA MEXICAN TRAY': 386,
 'FULL ENGLISH BREAKFAST PLATE': 385,
 'RECIPE BOX BLUE SKETCHBOOK DESIGN': 384,
 'CERAMIC CAKE STAND + HANGING CAKES': 384,
 'WOODEN HAPPY BIRTHDAY GARLAND': 383,
 'SET 12 RETRO WHITE CHALK STICKS': 381,
 'RETROSPOT TEA SET CERAMIC 11 PC ': 381,
 'CAKE STAND 3 TIER MAGIC GARDEN': 381,
 'LAVENDER SCENTED FABRIC HEART': 379,
 'CHARLIE+LOLA PINK HOT WATER BOTTLE': 379,
 'KINGS CHOICE TEA CADDY ': 379,
 'ROUND CONTAINER SET OF 5 RETROSPOT': 378,
 'RECIPE BOX WITH METAL HEART': 377,
 'RED SPOTTY PEG BAG': 377,
 'SET OF 3 COLOURED  FLYING DUCKS': 377,
 'PINK  SPOTTY CUP': 377,
 'CERAMIC CHERRY CAKE MONEY BANK': 376,
 'WOODEN UNION JACK BUNTING': 376,
 'RED SPOT CERAMIC DRAWER KNOB': 375,
 'CERAMIC CAKE DESIGN SPOTTED MUG': 374,
 'RIBBON REEL HEARTS DESIGN ': 374,
 'ANTIQUE SILVER TEA GLASS ENGRAVED': 373,
 'FAIRY CAKE FLANNEL ASSORTED COLOUR': 372,
 'BLUE  SPOTTY CUP': 372,
 'CHARLIE + LOLA RED HOT WATER BOTTLE': 371,
 'ALARM CLOCK BAKELIKE RED ': 371,
 'RETROSPOT HEART HOT WATER BOTTLE': 370,
 'ANTIQUE LILY FAIRY LIGHTS': 369,
 'PACK OF 12 TRADITIONAL CRAYONS': 368,
 'SET/3 RED GINGHAM ROSE STORAGE BOX': 367,
 'KEY FOB , GARAGE DESIGN': 366,
 'FANCY FONT BIRTHDAY CARD, ': 366,
 'FAMILY ALBUM WHITE PICTURE FRAME': 365,
 'CHARLOTTE BAG , PINK/WHITE SPOTS': 364,
 'RED RETROSPOT SUGAR JAM BOWL': 364,
 'COFFEE MUG DOG + BALL DESIGN': 364,
 'RED SPOTS  WRAP ': 364,
 'STRAWBERRY SHOPPER BAG': 363,
 'ROTATING SILVER ANGELS T-LIGHT HLDR': 363,
 'COWBOYS AND INDIANS BIRTHDAY CARD ': 363,
 'PINK FAIRY CAKE CHILDRENS APRON': 363,
 'PICNIC BASKET WICKER LARGE': 362,
 'GLASS HONEYPOT WASP CATCHER': 362,
 'RED WHITE SCARF  HOT WATER BOTTLE': 362,
 'CHRISTMAS GINGHAM HEART': 361,
 'SET OF 6 RIBBONS VINTAGE CHRISTMAS': 360,
 'WOODEN CROQUET GARDEN SET': 359,
 'HEART DECORATION WITH PEARLS ': 359,
 'METAL SIGN,CUPCAKE SINGLE HOOK': 357,
 'MINI PAINT SET VINTAGE ': 357,
 'GLASS  BEURRE DISH': 357,
 "YOU'RE CONFUSING ME METAL SIGN ": 356,
 'SANDWICH BATH SPONGE': 355,
 'ALARM CLOCK BAKELIKE GREEN': 354,
 'MAGIC DRAWING SLATE SPACEBOY ': 354,
 'VINTAGE CREAM 3 BASKET CAKE STAND': 353,
 'PINK SPOTTY BOWL': 353,
 'GIN AND TONIC MUG': 352,
 'RED SPOTTY OVEN GLOVE ': 352,
 "POPPY'S PLAYHOUSE KITCHEN": 350,
 'PINK CHERRY LIGHTS': 349,
 'BIG DOUGHNUT FRIDGE MAGNETS': 349,
 'PACK OF 12 LONDON TISSUES ': 349,
 'PARTY CONE CHRISTMAS DECORATION ': 349,
 'SKULLS  WATER TRANSFER TATTOOS ': 349,
 'MULTI COLOUR SILVER T-LIGHT HOLDER': 348,
 'CHARLOTTE BAG , SUKI DESIGN': 347,
 'S/6 WOODEN SKITTLES IN COTTON BAG': 346,
 'BATH BUILDING BLOCK WORD': 343,
 'BAG 250g SWIRLY MARBLES': 342,
 'PICTURE FRAME WOOD TRIPLE PORTRAIT': 341,
 '12 PENCILS TALL TUBE SKULLS': 341,
 '12 PENCIL SMALL TUBE WOODLAND': 339,
 'FAIRY CAKE DESIGN UMBRELLA': 338,
 'VINTAGE UNION JACK MEMOBOARD': 337,
 'RED RETROSPOT BUTTER DISH': 336,
 'PINK FLORAL FELTCRAFT SHOULDER BAG': 336,
 'BOX OF VINTAGE ALPHABET BLOCKS': 336,
 'PORCELAIN BUTTERFLY OIL BURNER': 335,
 'NOEL WOODEN BLOCK LETTERS ': 335,
 'LUNCH BAG RED RETROSPOT': 335,
 'HOT WATER BOTTLE BABUSHKA ': 335,
 'AGED GLASS SILVER T-LIGHT HOLDER': 335,
 'LUNCH BAG DOLLY GIRL DESIGN': 334,
 'VINTAGE KID DOLLY CARD ': 334,
 'BROWN CHECK CAT DOORSTOP ': 333,
 'WOODEN HEART CHRISTMAS SCANDINAVIAN': 333,
 'RED FLORAL FELTCRAFT SHOULDER BAG': 332,
 'HOOK, 1 HANGER ,MAGIC GARDEN': 332,
 'SET/6 PINK  BUTTERFLY T-LIGHTS': 331,
 'VINTAGE BILLBOARD DRINK ME MUG': 331,
 'DOOR MAT ENGLISH ROSE ': 330,
 'MINI WOODEN HAPPY BIRTHDAY GARLAND': 330,
 'LUSH GREENS RIBBONS': 330,
 'PACK OF 20 SKULL PAPER NAPKINS': 330,
 'CARD HOLDER GINGHAM HEART': 329,
 'BOX OF VINTAGE JIGSAW BLOCKS ': 329,
 'ELEPHANT, BIRTHDAY CARD, ': 329,
 'SET/10 BLUE SPOTTY PARTY CANDLES': 329,
 'CHILDS BREAKFAST SET DOLLY GIRL ': 328,
 'STRAWBERRY FAIRY CAKE TEAPOT': 328,
 'SKULL SHOULDER BAG': 328,
 'MOROCCAN TEA GLASS': 328,
 'SKULL LUNCH BOX WITH CUTLERY ': 327,
 'MINT KITCHEN SCALES': 327,
 "POPPY'S PLAYHOUSE BEDROOM ": 326,
 'DOOR MAT HEARTS': 326,
 'BALLOONS  WRITING SET ': 325,
 'CHARLOTTE BAG PINK WITH WHITE SPOTS': 325,
 'INFLATABLE POLITICAL GLOBE ': 324,
 'GIN & TONIC DIET GREETING CARD ': 324,
 'WEEKEND BAG VINTAGE ROSE PAISLEY': 324,
 'RETRO SPOT SMALL MILK JUG': 324,
 'CHILDRENS APRON SPACEBOY DESIGN': 323,
 'AIRLINE BAG VINTAGE TOKYO 78': 323,
 'PACK 3 BOXES CHRISTMAS PANNETONE': 323,
 'CHILDS BREAKFAST SET SPACEBOY ': 323,
 'GARDEN METAL SIGN ': 323,
 'SET 3 RED SPOT TIN TEA,COFFEE,SUGAR': 320,
 'CHILDS BREAKFAST SET CIRCUS PARADE': 319,
 'CACTI T-LIGHT CANDLES': 319,
 'SET/5 RED RETROSPOT LID GLASS BOWLS': 319,
 'ENAMEL FLOWER JUG CREAM': 319,
 'WHITE JEWELLED HEART DECORATION': 319,
 'BLACK/BLUE DOTS RUFFLED UMBRELLA': 318,
 'COLOURING PENCILS BROWN TUBE': 318,
 'SET OF 20 KIDS COOKIE CUTTERS': 317,
 '15CM CHRISTMAS GLASS BALL 20 LIGHTS': 317,
 'RETRO SPOT TRADITIONAL TEAPOT ': 317,
 'POTTERING MUG': 317,
 'VINTAGE UNION JACK DOORSTOP': 316,
 'HEART DECORATION PAINTED ZINC ': 316,
 'GLITTER HANGING BUTTERFLY STRING': 316,
 'BLUE SPOTTY BOWL': 315,
 'BLUE HAPPY BIRTHDAY BUNTING': 315,
 'FELTCRAFT CHRISTMAS FAIRY': 314,
 'SLATE TILE NATURAL HANGING': 312,
 'CHILDS APRON SPACEBOY DESIGN': 312,
 'MA CAMPAGNE CUTLERY BOX': 311,
 'STRAWBERRY BATH SPONGE ': 311,
 '36 PENCILS TUBE WOODLAND': 311,
 'WHITE WIRE EGG HOLDER': 311,
 'SLEEPING CAT ERASERS': 311,
 '36 PENCILS TUBE SKULLS': 310,
 'ENAMEL BREAD BIN CREAM': 310,
 'DELUXE SEWING KIT ': 310,
 '3 HOOK PHOTO SHELF ANTIQUE WHITE': 309,
 'APPLE BATH SPONGE': 309,
 'OWL DOORSTOP': 309,
 'PACK OF 12 WOODLAND TISSUES ': 308,
 'FUNKY WASHING UP GLOVES ASSORTED': 308,
 '20 DOLLY PEGS RETROSPOT': 308,
 'RETROSPOT CHILDRENS APRON': 307,
 'SAVE THE PLANET COTTON TOTE BAG': 307,
 'CITRONELLA CANDLE GARDEN POT': 307,
 'WASH BAG VINTAGE ROSE PAISLEY': 306,
 'SMALL HEART FLOWERS HOOK ': 306,
 'ENGLISH ROSE NOTEBOOK A7 SIZE': 304,
 'RIBBON REEL LACE DESIGN ': 304,
 'BRIGHT BLUES RIBBONS ': 303,
 'KINGS CHOICE BISCUIT TIN': 303,
 'WATERING CAN BLUE ELEPHANT': 303,
 'PIGGY BANK RETROSPOT ': 302,
 'HANGING METAL STAR LANTERN': 302,
 'RED SPOTTY CHILDS APRON': 300,
 'CAMOUFLAGE LED TORCH': 300,
 'SET 10 LIGHTS NIGHT OWL': 300,
 'KINGS CHOICE CIGAR BOX MATCHES ': 299,
 'VICTORIAN SEWING BOX MEDIUM': 299,
 'PINK HEART DOTS HOT WATER BOTTLE': 298,
 'DECORATION, HANGING HEART+MIRROR ': 298,
 '10 COLOUR SPACEBOY PEN': 298,
 'COFFEE MUG APPLES DESIGN': 297,
 'HAND WARMER BABUSHKA DESIGN': 296,
 'HOME SMALL WOOD LETTERS': 296,
 'MOUSE TOY WITH PINK T-SHIRT': 296,
 'SET OF 6 SOLDIER SKITTLES': 294,
 'ENCHANTED BIRD COATHANGER 5 HOOK': 294,
 'SET OF 9 HEART SHAPED BALLOONS': 293,
 'CAKE STAND WHITE TWO TIER LACE': 293,
 'ROBOT BIRTHDAY CARD': 293,
 'BAG 125g SWIRLY MARBLES': 292,
 'DOOR MAT 3 SMILEY CATS': 292,
 'PAPER BUNTING VINTAGE PAISLEY': 292,
 'EMPIRE BIRTHDAY CARD': 291,
 'ROMANTIC PINKS RIBBONS ': 291,
 'DINOSAURS  WRITING SET ': 290,
 'FRYING PAN UNION FLAG': 290,
 'RED SPOTTY PLATE ': 290,
 'WOODEN STAR CHRISTMAS SCANDINAVIAN': 289,
 'ROCKING HORSE RED CHRISTMAS ': 288,
 'DOOR MAT SPOTTY HOME SWEET HOME': 288,
 'DOORMAT SPOTTY HOME SWEET HOME': 287,
 'KEY FOB , FRONT  DOOR ': 287,
 'TRADITIONAL KNITTING NANCY': 287,
 'CIRCUS PARADE LUNCH BOX ': 286,
 'CHRISTMAS RETROSPOT HEART WOOD': 286,
 'GAOLERS KEYS DECORATIVE GARDEN ': 285,
 'CHOCOLATE CALCULATOR': 285,
 'CERAMIC CAKE BOWL + HANGING CAKES': 284,
 'RED RETROSPOT STORAGE JAR': 284,
 '36 PENCILS TUBE RED SPOTTY': 284,
 'JUMBO BAG CHARLIE AND LOLA TOYS': 284,
 'KINGS CHOICE MUG': 283,
 'BABUSHKA LIGHTS STRING OF 10': 282,
 'METAL SIGN EMPIRE TEA': 282,
 '12 PENCILS TALL TUBE WOODLAND': 282,
 'CERAMIC CAKE DESIGN SPOTTED PLATE': 281,
 'RIBBON REEL SPOTS DESIGN ': 281,
 'GREEN GINGHAM FLOWER JEWELLERY BOX': 281,
 'WHITE BEADED GARLAND STRING 20LIGHT': 281,
 'UNION JACK FLAG LUGGAGE TAG': 280,
 'LUNCH BOX WITH CUTLERY FAIRY CAKES ': 279,
 'ROSE CARAVAN DOORSTOP': 278,
 'ENAMEL MEASURING JUG CREAM': 277,
 'FELTCRAFT PRINCESS CHARLOTTE DOLL': 276,
 'CAKE STAND LACE WHITE': 276,
 'PINK REGENCY TEACUP AND SAUCER': 276,
 'BLACK RECORD COVER FRAME': 276,
 'RIBBON REEL CHRISTMAS SOCK BAUBLE': 276,
 'GROW YOUR OWN BASIL IN ENAMEL MUG': 276,
 'PACK OF 12 RED SPOTTY TISSUES ': 275,
 'SET/6 TURQUOISE BUTTERFLY T-LIGHTS': 275,
 'WOODLAND PARTY BAG + STICKER SET': 275,
 'CHILDS GARDEN TROWEL PINK': 275,
 'PACK OF 12 SKULL TISSUES': 274,
 'COOKING SET RETROSPOT': 274,
 '12 PENCILS TALL TUBE RED SPOTTY': 273,
 'HAPPY STENCIL CRAFT': 273,
 'DOOR MAT WELCOME PUPPIES': 272,
 'CHOCOLATE BOX RIBBONS ': 272,
 'ADVENT CALENDAR GINGHAM SACK': 272,
 'SMALL PURPLE BABUSHKA NOTEBOOK ': 271,
 'PHARMACIE FIRST AID TIN': 271,
 'METAL MERRY CHRISTMAS WREATH': 270,
 'CHILDRENS GARDEN GLOVES PINK': 270,
 'PHOTO CUBE': 270,
 'WRAP PINK FAIRY CAKES ': 269,
 'S/4 PINK FLOWER CANDLES IN BOWL': 269,
 'ORGANISER WOOD ANTIQUE WHITE ': 269,

In [35]:
# data.to_excel('cleaned_online_retail.xlsx',index=False)

In [37]:
data['InvoiceDate'].min()

Timestamp('2009-12-01 07:45:00')

In [38]:
data['InvoiceDate'].max()

Timestamp('2010-12-09 20:01:00')